const menu = [
  {
    name: "Original Milk Tea",
    inStock: "No",
    MilkTea: true,
    img: "imgs/Original Milk Tea.png",
    whalen: true,
    reccomend: true,
  },
  {
    name: "Thai Tea",
    inStock: "Yes",
    MilkTea: false,
    img: "imgs/Thai Tea.png",
    whalen: false,
    reccomend: true,
  },
  {
    name: "Passionfruit Tea",
    inStock: "Yes",
    MilkTea: false,
    img: "imgs/Passionfruit Tea.png",
    whalen: false,
    reccomend: true,
  },
  {
    name: "Strawberry Tea",
    inStock: "No",
    MilkTea: false,
    img: "imgs/Strawberry Tea.png",
    whalen: false,
    reccomend: true,
  },
  {
    name: "Brown Sugar Oolong Tea",
    inStock: "Yes",
    MilkTea: false,
    img: "imgs/Brown Sugar Oolong Tea.png",
    whalen: true,
    reccomend: false,
  },
  {
    name: "Brown Sugar Milk Tea",
    inStock: "No",
    MilkTea: true,
    img: "imgs/Brown Sugar Milk Tea.png",
    whalen: false,
    reccomend: false,
  },
  {
    name: "Matcha Tea",
    inStock: "Yes",
    MilkTea: false,
    img: "imgs/Matcha Tea.png",
    whalen: false,
    reccomend: true,
  },
  {
    name: "Taro Milk Tea",
    inStock: "Yes",
    MilkTea: true,
    img: "imgs/Taro Milk Tea.png",
    whalen: false,
    reccomend: false,
  },
  {
    name: "Lychee Green Tea",
    inStock: "Yes",
    MilkTea: false,
    img: "imgs/Lychee Green Tea.png",
    whalen: false,
    reccomend: true,
  },
  {
    name: "Oreo Milk Tea",
    inStock: "No",
    MilkTea: true,
    img: "imgs/Oreo Milk Tea.png",
    whalen: false,
    reccomend: false,
  },
];

export { menu };
