const menu = [
  {
    name: "Original Milk Tea",
    inStock: "No",
    MilkTea: true,
    img: "imgs/Original Milk Tea.png",
    whalen: true,
    reccomend: true,
  },
  {
    name: "Thai Milk Tea",
    inStock: "Yes",
    MilkTea: true,
    img: "imgs/Original Milk Tea.png",
    whalen: false,
    reccomend: true,
  },
  {
    name: "Passionfruit Green Tea",
    inStock: "Yes",
    MilkTea: false,
    img: "imgs/Original Milk Tea.png",
    whalen: false,
    reccomend: true,
  },
  {
    name: "Strawberry Green Tea",
    inStock: "No",
    MilkTea: false,
    img: "imgs/Original Milk Tea.png",
    whalen: false,
    reccomend: true,
  },
  {
    name: "Black Sugar Oolong Tea",
    inStock: "Yes",
    MilkTea: false,
    img: "imgs/Original Milk Tea.png",
    whalen: true,
    reccomend: false,
  },
  {
    name: "Brown Sugar Milk Tea",
    inStock: "No",
    MilkTea: true,
    img: "imgs/Original Milk Tea.png",
    whalen: false,
    reccomend: false,
  },
  {
    name: "Matcha Milk Tea",
    inStock: "Yes",
    MilkTea: true,
    img: "./imgs/Original Milk Tea.png",
    whalen: false,
    reccomend: true,
  },
  {
    name: "Taro Milk Tea",
    inStock: "Yes",
    MilkTea: true,
    img: "imgs/Original Milk Tea.png",
    whalen: false,
    reccomend: false,
  },
  {
    name: "Lychee Green Tea",
    inStock: "Yes",
    MilkTea: false,
    img: "imgs/Original Milk Tea.png",
    whalen: false,
    reccomend: true,
  },
  {
    name: "Oreo Milk Tea",
    inStock: "No",
    MilkTea: true,
    img: "imgs/Original Milk Tea.png",
    whalen: false,
    reccomend: false,
  },
];

export { menu };
